#!/bin/bash
# author   : chinatree <chinatree2012@gmail.com>
# date     : 2012-12-21
#
# This shell script takes care of starting and stopping l2tpd.
#
# chkconfig: - 80 30
# the script ion: Layer 2 Tunnelling Protocol Daemon (RFC 2661)
#
# processname: xl2tpd
# config: /etc/xl2tpd/xl2tpd.conf
# pidfile: /etc/xl2tpd/logs/xl2tpd.pid

#Servicename
PREFIX=/usr/local/services/xl2tpd
SERVICE=xl2tpd
XL2TPD_BIN=$PREFIX/sbin/$SERVICE
ETC_FILE=$PREFIX/etc/$SERVICE.conf

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

if [ ${NETWORKING} = "no" ]
then
    exit 0
fi

[ -x $XL2TPD_BIN ] || exit 0

RETVAL=0

start() {
    echo -n "Starting $SERVICE: "
    if [ ! -d /var/run/xl2tpd ]
    then
        mkdir /var/run/xl2tpd
    fi

    daemon ${XL2TPD_BIN} -c $ETC_FILE
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
    echo ""
    return $RETVAL
}

stop() {
    echo -n "Stopping $SERVICE: "
    killproc $SERVICE
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$SERVICE
    return $RETVAL
}

restart() {
    stop
    start
}

# See how we were called.
case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
status)
    status $SERVICE
    RETVAL=$?
    ;;
restart|reload)
    restart
    ;;
condrestart)
    [ -f /var/lock/subsys/$SERVICE ] && restart || :
    ;;
*)
    echo "Usage: $SERVICE {start|stop|status|restart|reload|condrestart}"
    exit 1
esac
