#!/bin/bash
# Author  : chinatree <chinatree2012@gmail.com>
# Date    : 2014-06-24
# Version : 1.1
#chkconfig:345 62 62
# Description: Nginx Server

RETVAL=0
prog="nginx"

# [global]
SCRIPT_PATH=$(cd "$(dirname "$0")"; pwd)
SCRIPT_NAME=$(basename "$0")
NGINX_BIN="/usr/local/services/nginx/sbin/nginx"
PARA_NUM="$#"
PROC_PID="$$"

get_color() {
    case "$2" in
    RED)
        echo -ne "\033[31m"$1"\033[0m"
        ;;
    GREEN)
        echo -ne "\033[32m"$1"\033[0m"
        ;;
    PEACH)
        echo -ne "\033[1;31;40m"$1"\033[0m"
        ;;
    *)
        echo -ne "$1"
        ;;
    esac
}

get_exit_code() {
    if [ "${1}" -ne 0 ];then
        echo "[`get_color " FAILED " RED`]"
        exit "${1}"
    else
        echo "[`get_color "   OK   " GREEN`]"
    fi
}

get_fixed_width() {
    local str="${1:-NONE}"
    local length="${2:-0}"
    local isEnter="${3:-NONE}"
    case "${length:-NONE}" in
    12)
        printf "%-12s" "${str}"
        ;;
    20)
        printf "%-20s" "${str}"
        ;;
    50)
        printf "%-50s" "${str}"
        ;;
    66)
        printf "%-66s" "${str}"
        ;;
    88)
        printf "%-88s" "${str}"
        ;;
    *)
        printf "%${length}s" "${str}"
        ;;
    esac
    if [ "${isEnter}" = "Y" ];
    then
        echo -ne "\n";
    fi
}

start() {
    get_fixed_width "Starting up ${prog}: " '50'
    ${NGINX_BIN}
    RETVAL=$?    
    get_exit_code ${RETVAL}
    return ${RETVAL} 
}

stop() {
    get_fixed_width "Shutting down ${prog}: " '50'
    ${NGINX_BIN} -s stop
    RETVAL=$?
    get_exit_code ${RETVAL}
    return ${RETVAL}
}

synax() {
    echo "Checking ${prog} config: "
    ${NGINX_BIN} -t
    RETVAL=$?
    return ${RETVAL} 
}

reload() {
    echo -n "Reloading service ${prog}: "
    ${NGINX_BIN} -s reload
    RETVAL=$?
    get_exit_code ${RETVAL}
    return ${RETVAL}    
}

check_running() {
    local ret=1
    return ${ret}
}

log() {
    local str="${1-... }"
    echo "* `get_color " ${str} " PEACH`"
    return 0
}

check() {
    test "${USERNAME}" != "root" && log "This script must be run by root!" && exit 1
    ! test -x ${NGINX_BIN} && log "${NGINX_BIN} does not exist or is not an executable file!" && exit 1
    return 0
}

usage() {
    echo -e "`get_color "Usage:" CYANBLUE` \
    \n    ./${SCRIPT_NAME} {start|stop|restart|synax|reload}"
    exit 2
}

check
case "$1" in
start)
    start
    RETVAL=$?
    ;;
stop)
    stop
    RETVAL=$?
    ;;
restart)
    stop
    sleep 1s
    start
    RETVAL=$?
    ;;
synax)
    synax
    RETVAL=$?
    ;;
reload)
    reload
    RETVAL=$?
    ;;
*)
    usage
    ;;
esac

exit ${RETVAL}
